### ISSUE TITLE
自己紹介データ移行

### ISSUE THREAD

**Issue by supleiades** [mo9mo9study/discord.selfIntroduction-datadump#3]
- Discordギルドチャンネル管理からDBに切り替える
- 現行、１チャンネルがDBでいう１レコードのように管理されている
- それを、json形式にdumpしてsqlalchemy経由でデータインポートする

**Comment by supleiades** [comment]
- テーブルのリセット（削除）
```sql
from sqlalchemy import Column, String, Integer, DateTime, Boolean
import os
import json
from collections import OrderedDict

import pandas as pd

from mo9mo9db.dbtables import Selfintroduction
from mo9mo9db.dbsession import get_db_engine

studymembers=[]
session = Selfintroduction.session()
engine = get_db_engine()

Selfintroduction.__table__.drop(engine)
```

**Comment by supleiades** [comment]
https://github.com/mo9mo9study/discord.selfIntroduction-datadump/blob/master/src/main.py
この処理を起動して必要な自己紹介データをjsonファイルに書き込む

**Comment by supleiades** [comment]
```sql
mysql> SELECT count(*) FROM selfintroduction;
+----------+
| count(*) |
+----------+
|      379 |
+----------+
1 row in set (0.01 sec)
```

**Comment by supleiades** [comment]
- 起動テスト中
- https://github.com/mo9mo9study/discord.CodeWarehouse/blob/supleiades/20211107/fix-124-dbVersionOfSelfintroduction/management.py
```py
--------------------
起動中...
BOT NAME : プールの監視員
BOT ID : 618077392686153742
--------------------
自己紹介を送信していないユーザー: watanabe#3968/828139167266504724
complete: watanabe#3968
Ignoring exception in on_ready
Traceback (most recent call last):
  File "/home/centos/staging/discord.CodeWarehouse/venv/lib/python3.8/site-packages/discord/client.py", line 343, in _run_event
    await coro(*args, **kwargs)
  File "/home/centos/staging/discord.CodeWarehouse/Cogs/Managements/languageVisualization.py", line 40, in on_ready
    await self.message.add_reaction(languages["emoji"])
  File "/home/centos/staging/discord.CodeWarehouse/venv/lib/python3.8/site-packages/discord/message.py", line 1223, in add_reaction
    await self._state.http.add_reaction(self.channel.id, self.id, emoji)
  File "/home/centos/staging/discord.CodeWarehouse/venv/lib/python3.8/site-packages/discord/http.py", line 248, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 30010): Maximum number of reactions reached (20)
```

**Comment by supleiades** [comment]
mo9mo9study/discord.CodeWarehouse#124

## 確認用垢からギルド参加から確認
- 参加時OK
![image](https://user-images.githubusercontent.com/45380191/144756320-a63b942f-81fb-42e8-84ed-e4a374978db8.png)

- メッセージの内容OK
![image](https://user-images.githubusercontent.com/45380191/144756330-f641cf76-ab91-4327-8847-fbf5d979a8dd.png)

- 投稿前のリセットOK
![image](https://user-images.githubusercontent.com/45380191/144755278-ba12b4e2-6807-4ae6-b5fe-362740d69f9b.png)

- 初回送信時OK
![image](https://user-images.githubusercontent.com/45380191/144756364-60509420-e2d3-4681-9612-487dd7609050.png)
![image](https://user-images.githubusercontent.com/45380191/144756371-887ed31c-0951-427a-9381-b5edb071df14.png)


-  ¥preditから送信済みの自己紹介リセットで修正OK
![image](https://user-images.githubusercontent.com/45380191/144756412-07a2aab3-423a-4545-8c74-b3273a1c67b1.png)

- 過去の自己紹介削除OK
![image](https://user-images.githubusercontent.com/45380191/144756426-89fe341d-66df-4862-92f3-51bbcfcb6393.png)

- 項目一つずつ修正OK
![image](https://user-images.githubusercontent.com/45380191/144756540-9f6de7a9-5bdd-4d9a-bb95-f0e59e81832e.png)

- 自己紹介のログOK
![image](https://user-images.githubusercontent.com/45380191/144756570-f93f3e42-0614-4160-bb5d-6ea40e97d721.png)

**Comment by supleiades** [comment]
mo9mo9study/discord.CodeWarehouse#124

- 自己紹介のmsgが削除されているが、DB上では既に送信済みの時に自己紹介修正OK
![image](https://user-images.githubusercontent.com/45380191/144756637-fd72fb25-6be8-40b4-8a26-f2aa6cb69145.png)

# josnでデータ移行したユーザーの自己紹介修正
- 8/15に投稿した過去の自己紹介
![image](https://user-images.githubusercontent.com/45380191/144756752-1fc91c47-d6a6-43e1-b4da-05564d84773e.png)
- 新しい自己紹介
![image](https://user-images.githubusercontent.com/45380191/144756763-043e5f59-31f7-4fcf-882d-12d0a80373c6.png)
- 想定通り削除されたことを確認

## bot_log
```
[WARN] KeiitiChanの自己紹介を送信しましたが、過去の自己紹介の削除に失敗しました
[INFO] SuPleiadesの過去の自己紹介を削除し、新しい自己紹介を送信しました
```
